### ISSUE TITLE
Add ability to secure items through permissions api

### ISSUE THREAD

**Issue by dvbarnes** [relativitydev/relativity-test-helpers#10]
I have a few tests where I need to ensure my system is returning the correct values based on group permissions

**Comment by ppande1020** [comment]
I would love to work on something like this. The permissions API is fascinating to me.

**Comment by dvbarnes** [comment]
I'm working on it now can you get #9 approved first?

**Comment by ppande1020** [comment]
Yep, working on it.

**Comment by dvbarnes** [comment]
#12

**Comment by ppande1020** [comment]
David, if you approve the invite link I sent out, you should be able to merge future changes. We can still review your changes to make sure everything is good to go but you should be able to merge the change once it's approved.
