### ISSUE TITLE
Start unit testing some of these methods.

### ISSUE THREAD

**Issue by dvbarnes** [relativitydev/relativity-test-helpers#11]
I would like to openly start discussing adding some tests to this project seeing as many people will be contributing to it, making sure changes don't break for others will be helpful. Starting off I have a few questions.

I know Relativity uses nunit for tests do we want to use nunit for this project as well?
Do we want to add some CI/CD for PRs that pass certain gates?
- I know this can open a bag of worms into managing the project but starting the discussion now should help future people.

**Comment by ppande1020** [comment]
I would prefer to keep our framework consistent with what we use internally here at Relativity, so I can continue adding helpers without having to change anything. What are our options if we dont proceed with NUnit? 

Open to ideas about CI/CD. I think it would be really cool to have tests and a continuous integration cycle set up for this project.

**Comment by dvbarnes** [comment]
we use [xunit ](https://xunit.github.io/) here, I really like it. But I think for the sake of consistency since Relativity does own the project now that we should stick with NUnit.

As for CI/CD I think this will be somewhat challenging until we have a plan around how to manage the Relativity dlls, I will think more on this and we can discuss options. As an ask for you can you add the nugspec file as part of the repo? It's not a huge priority it's just good practice so the repo is self containing.

**Comment by ppande1020** [comment]
The nugspec is something I am looking into. I plan to have something by end of the week.
