### ISSUE TITLE
Create/Setup Unit tests

### ISSUE THREAD

**Issue by TommyBigNose** [relativitydev/relativity-test-helpers#63]
As we use this more and more, I feel like we should create tests for this to make sure any updates are fine before merging into Develop and creating NuGet packages.

Specifically, we need tests on TestHellpers.cs.  Recently, connecting to another instance was added as a feature and it needed some unit tests because some minor issues kept cropping up due to not being able to fully run through ti until we got the new package.

**Comment by calimetikcura** [comment]
Integration tests has been written for TestHelpers around Feb 2020. So we are closing the issue.
