### ISSUE TITLE
remove Hard NUnit Framework dependency

### ISSUE THREAD

**Issue by dvbarnes** [relativitydev/relativity-test-helpers#87]
It seems the TestHelper constructor takes in a NUnit.Framework.TestContext testContext as a parameter. We do not use NUnit which is causing some interesting errors related to XUnit and Nunit installed together. Removing this dependency and using a class specific to the domain of the TestHelper will overall make things much beter.

**Comment by jake-martin** [comment]
Hi @dvbarnes, we're going to remove this dependency in a future version of Test Helpers ([see here](https://community.relativity.com/s/feed/0D51T00007Ma8Y7SAJ)). In the meantime, you can use this [Early Access release](https://www.nuget.org/packages/RelativityDev.RelativityTestHelpers/8.0.0.1-EA-1) of Test Helpers that has the NUnit dependency removed.
