### ISSUE TITLE
User create fails no indication

### ISSUE THREAD

**Issue by dvbarnes** [relativitydev/relativity-test-helpers#98]
Was trying to use [Create user ](https://github.com/relativitydev/relativity-test-helpers/blob/948df348c0e742c8e59bb2c90edc96b9a59d3c72/Source/Relativity.Test.Helpers/Relativity.Test.Helpers/UserHelpers/CreateUser.cs#L146) and noticed I was getting a 0 as a return value. After digging in, it turns out the create user function does not double check the success flag and throws an error if the request failed. Please throw an error if create fails

**Comment by aarongilbert123** [comment]
Fixed in this pull request: https://github.com/relativitydev/relativity-test-helpers/pull/99
